import { Campagne } from "./types";

export const campagnes: Campagne[] = [
  {
    id: 1,
    nom: "Sensibilisation Q1 2026 - Phishing bancaire",
    dateLancement: "15/01/2026",
    statut: "Terminée",
    templateMail: "Alerte sécurité bancaire",
    templatePage: "Page de connexion bancaire",
    url: "https://phishing-test.example.com/campagne-q1-securite-mdp",
  },
  {
    id: 2,
    nom: "Test Microsoft 365 - Département IT",
    dateLancement: "22/01/2026",
    statut: "En cours",
    templateMail: "Notification Microsoft",
    templatePage: "Portail Microsoft 365",
    url: "https://phishing-test.example.com/rh-test",
  },
  {
    id: 3,
    nom: "Formation PayPal - Comptabilité",
    dateLancement: "05/02/2026",
    statut: "Planifiée",
    templateMail: "PayPal - Confirmation de paiement",
    templatePage: "Page de vérification PayPal",
    url: "https://phishing-test.example.com/formation-nouveaux",
  },
  {
    id: 4,
    nom: "Campagne Google - Tous les employés",
    dateLancement: "28/01/2026",
    statut: "En cours",
    templateMail: "Google - Nouvelle connexion",
    templatePage: "Interface de réinitialisation Google",
    url: "https://phishing-test.example.com/simulation-finance",
  },
  {
    id: 5,
    nom: "Test Amazon - Service client",
    dateLancement: "10/01/2026",
    statut: "Terminée",
    templateMail: "Amazon - Problème de livraison",
    templatePage: "Connexion Amazon",
    url: "https://phishing-test.example.com/amazon-verify",
  },
  {
    id: 6,
    nom: "Formation LinkedIn - Recrutement RH",
    dateLancement: "18/02/2026",
    statut: "Planifiée",
    templateMail: "LinkedIn - Message recruteur",
    templatePage: "Page de connexion LinkedIn",
    url: "https://phishing-test.example.com/linkedin-login",
  },
  {
    id: 7,
    nom: "Sensibilisation Orange - Support technique",
    dateLancement: "03/02/2026",
    statut: "En cours",
    templateMail: "Orange - Facture impayée",
    templatePage: "Portail Orange",
    url: "https://phishing-test.example.com/orange-client",
  },
  {
    id: 8,
    nom: "Test Free Mobile - Direction",
    dateLancement: "12/01/2026",
    statut: "Terminée",
    templateMail: "Free Mobile - Mise à jour forfait",
    templatePage: "Interface Free Mobile",
    url: "https://phishing-test.example.com/free-mobile-auth",
  },
  {
    id: 9,
    nom: "Campagne La Poste - Logistique",
    dateLancement: "25/02/2026",
    statut: "Planifiée",
    templateMail: "La Poste - Colis en attente",
    templatePage: "Page de connexion La Poste",
    url: "https://phishing-test.example.com/laposte-services",
  },
  {
    id: 10,
    nom: "Formation Impôts - Département finance",
    dateLancement: "08/02/2026",
    statut: "Planifiée",
    templateMail: "Impots.gouv - Remboursement",
    templatePage: "Portail Impots.gouv.fr",
    url: "https://phishing-test.example.com/impots-gouv",
  },
  {
    id: 11,
    nom: "Test Ameli - Ressources humaines",
    dateLancement: "01/02/2026",
    statut: "En cours",
    templateMail: "Ameli - Mise à jour carte vitale",
    templatePage: "Interface Ameli",
    url: "https://phishing-test.example.com/ameli-compte",
  },
  {
    id: 12,
    nom: "Sensibilisation Netflix - Tous les services",
    dateLancement: "20/01/2026",
    statut: "Terminée",
    templateMail: "Netflix - Problème de paiement",
    templatePage: "Page de vérification Netflix",
    url: "https://phishing-test.example.com/netflix-payment",
  },
  {
    id: 13,
    nom: "Campagne Apple - Département IT",
    dateLancement: "14/02/2026",
    statut: "Planifiée",
    templateMail: "Apple - Achat suspect",
    templatePage: "Connexion Apple ID",
    url: "https://phishing-test.example.com/apple-id-security",
  },
  {
    id: 14,
    nom: "Formation Crédit Agricole - Finance",
    dateLancement: "29/01/2026",
    statut: "En cours",
    templateMail: "Crédit Agricole - Sécurité renforcée",
    templatePage: "Portail Crédit Agricole",
    url: "https://phishing-test.example.com/credit-agricole",
  },
  {
    id: 15,
    nom: "Test Société Générale - Comptabilité",
    dateLancement: "06/01/2026",
    statut: "Terminée",
    templateMail: "Société Générale - Opération bloquée",
    templatePage: "Interface Société Générale",
    url: "https://phishing-test.example.com/societe-generale",
  },
];
