import { ModeleMail } from "./types";

export const modelesMails: ModeleMail[] = [
  {
    id: 1,
    nom: "Alerte sécurité bancaire - Vérification urgente requise",
    expediteur: "securite@banque-nationale.com",
    objet: "⚠️ Action urgente requise - Vérification de votre compte",
    contenuHtml: `<html><body style="font-family: Arial, sans-serif; background-color: #f5f5f5; padding: 20px;"><table style="max-width: 600px; margin: 0 auto; background-color: white; border-radius: 5px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);"><tr><td style="padding: 30px;"><h1 style="color: #d32f2f; margin-top: 0;">⚠️ Alerte de Sécurité</h1><p>Votre compte a détecté une activité suspecte. Veuillez vérifier votre identité immédiatement.</p><a href="#" style="display: inline-block; background-color: #1976d2; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px; margin: 20px 0;">Vérifier maintenant</a></td></tr></table></body></html>`,
  },
  {
    id: 2,
    nom: "Notification Microsoft - Activité suspecte détectée",
    expediteur: "no-reply@account-microsoft.com",
    objet: "Activité inhabituelle sur votre compte Microsoft",
    contenuHtml: `<html><body style="font-family: 'Segoe UI', Arial, sans-serif; background-color: #f3f3f3; padding: 20px;"><table style="max-width: 600px; margin: 0 auto; background-color: white;"><tr><td style="padding: 20px; border-left: 4px solid #00a4ef;"><h2 style="color: #00a4ef; margin-top: 0;">Activité suspecte</h2><p>Une connexion depuis une nouvelle localisation a été détectée.</p><a href="#" style="background-color: #00a4ef; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px;">Examiner l'activité</a></td></tr></table></body></html>`,
  },
  {
    id: 3,
    nom: "PayPal - Confirmation de paiement requise",
    expediteur: "service@paypal-secure.com",
    objet: "Confirmez votre paiement de 249,99€",
    contenuHtml: `<html><body style="font-family: Arial, sans-serif; background-color: #f9f9f9; padding: 20px;"><table style="max-width: 600px; margin: 0 auto; background-color: white; border-radius: 8px;"><tr><td style="padding: 25px;"><h3 style="color: #003087;">Confirmation de paiement</h3><p>Nous avons enregistré une tentative de paiement de <strong>249,99€</strong>.</p><p>Cliquez ci-dessous pour confirmer:</p><a href="#" style="background-color: #003087; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px;">Confirmer le paiement</a></td></tr></table></body></html>`,
  },
  {
    id: 4,
    nom: "Google - Nouvelle connexion détectée",
    expediteur: "noreply@google-security.com",
    objet: "Nouvelle connexion depuis un appareil inconnu",
    contenuHtml: `<html><body style="font-family: Arial, sans-serif; background-color: #ffffff; padding: 20px;"><table style="max-width: 600px; margin: 0 auto; border: 1px solid #dadce0; border-radius: 8px;"><tr style="background-color: #f8f9fa;"><td style="padding: 15px; text-align: center;"><strong style="color: #1f2937;">Sécurité Google</strong></td></tr><tr><td style="padding: 20px;"><p>Nous avons détecté une nouvelle connexion à votre compte Google.</p><a href="#" style="background-color: #1f2937; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px; display: inline-block;">Vérifier l'activité</a></td></tr></table></body></html>`,
  },
  {
    id: 5,
    nom: "Amazon - Problème de livraison",
    expediteur: "commande@amazon-fr.com",
    objet: "Votre colis est bloqué - Action requise",
    contenuHtml: `<html><body style="font-family: Arial, sans-serif; background-color: #f5f5f5; padding: 20px;"><table style="max-width: 600px; margin: 0 auto; background-color: white;"><tr><td style="padding: 20px; border-top: 3px solid #FF9900;"><h3 style="color: #146eb4;">Problème de livraison</h3><p>Votre colis #ABC123456 ne peut pas être livré. Veuillez vérifier votre adresse.</p><a href="#" style="background-color: #FF9900; color: white; padding: 10px 20px; text-decoration: none; border-radius: 3px;">Corriger l'adresse</a></td></tr></table></body></html>`,
  },
  {
    id: 6,
    nom: "LinkedIn - Message important d'un recruteur",
    expediteur: "messages@linkedin-mail.com",
    objet: "Opportunité professionnelle exclusive pour vous",
    contenuHtml: `<html><body style="font-family: Arial, sans-serif; background-color: #f8f9f9; padding: 20px;"><table style="max-width: 600px; margin: 0 auto; background-color: white; border-radius: 8px;"><tr><td style="padding: 20px; color: #0a66c2;"><h3>Nouvelle opportunité</h3><p>Un recruteur vous a envoyé un message intéressant sur une position senior.</p><a href="#" style="background-color: #0a66c2; color: white; padding: 10px 20px; text-decoration: none; border-radius: 20px;">Voir le message</a></td></tr></table></body></html>`,
  },
  {
    id: 7,
    nom: "Orange - Facture impayée",
    expediteur: "factures@orange-client.fr",
    objet: "Votre facture de 89,90€ est en attente de paiement",
    contenuHtml: `<html><body style="font-family: Arial, sans-serif; background-color: #f5f5f5; padding: 20px;"><table style="max-width: 600px; margin: 0 auto; background-color: white;"><tr style="background-color: #FF6600;"><td style="padding: 15px; color: white; text-align: center;"><strong>Facture impayée</strong></td></tr><tr><td style="padding: 20px;"><p>Votre facture de <strong>89,90€</strong> est en attente.</p><a href="#" style="background-color: #FF6600; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px;">Payer maintenant</a></td></tr></table></body></html>`,
  },
  {
    id: 8,
    nom: "Free Mobile - Mise à jour du forfait",
    expediteur: "service-client@free-mobile.fr",
    objet: "Nouvelle offre exclusive - Mise à niveau gratuite",
    contenuHtml: `<html><body style="font-family: Arial, sans-serif; background-color: #f5f5f5; padding: 20px;"><table style="max-width: 600px; margin: 0 auto; background-color: white;"><tr><td style="padding: 20px; border-left: 4px solid #2d2d2d;"><h3 style="color: #2d2d2d; margin-top: 0;">Offre exclusive</h3><p>Bénéficiez d'une mise à niveau gratuite de votre forfait!</p><a href="#" style="background-color: #2d2d2d; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px;">Accepter l'offre</a></td></tr></table></body></html>`,
  },
  {
    id: 9,
    nom: "La Poste - Colis en attente",
    expediteur: "suivi@laposte-tracking.fr",
    objet: "Votre colis attend au centre de tri",
    contenuHtml: `<html><body style="font-family: Arial, sans-serif; background-color: #f5f5f5; padding: 20px;"><table style="max-width: 600px; margin: 0 auto; background-color: white;"><tr><td style="padding: 20px;"><h3 style="color: #003f7f;">Colis en attente</h3><p>Votre colis #LP123456 attend à notre centre de tri.</p><a href="#" style="background-color: #003f7f; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px;">Suivre le colis</a></td></tr></table></body></html>`,
  },
  {
    id: 10,
    nom: "Impots.gouv - Remboursement en attente",
    expediteur: "noreply@impots-gouv.fr",
    objet: "Remboursement d'impôts de 487,50€ à récupérer",
    contenuHtml: `<html><body style="font-family: Arial, sans-serif; background-color: #f5f5f5; padding: 20px;"><table style="max-width: 600px; margin: 0 auto; background-color: white;"><tr style="background-color: #4e7ba1;"><td style="padding: 15px; color: white; text-align: center;"><strong>Remboursement en attente</strong></td></tr><tr><td style="padding: 20px;"><p>Un remboursement de <strong>487,50€</strong> est prêt à être versé.</p><a href="#" style="background-color: #4e7ba1; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px;">Réclamer le remboursement</a></td></tr></table></body></html>`,
  },
  {
    id: 11,
    nom: "Ameli - Mise à jour carte vitale",
    expediteur: "contact@ameli-assurance.fr",
    objet: "Votre carte Vitale expire bientôt",
    contenuHtml: `<html><body style="font-family: Arial, sans-serif; background-color: #f5f5f5; padding: 20px;"><table style="max-width: 600px; margin: 0 auto; background-color: white;"><tr><td style="padding: 20px; border-left: 4px solid #0066aa;"><h3 style="color: #0066aa; margin-top: 0;">Carte Vitale expirée</h3><p>Votre carte Vitale expire le mois prochain.</p><a href="#" style="background-color: #0066aa; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px;">Renouveler la carte</a></td></tr></table></body></html>`,
  },
  {
    id: 12,
    nom: "Netflix - Problème de paiement",
    expediteur: "billing@netflix-account.com",
    objet: "Échec du paiement - Mettez à jour vos informations",
    contenuHtml: `<html><body style="font-family: Arial, sans-serif; background-color: #000000; padding: 20px;"><table style="max-width: 600px; margin: 0 auto; background-color: #221f1f;"><tr><td style="padding: 20px;"><h3 style="color: #e50914; margin-top: 0;">Problème de paiement</h3><p style="color: #ffffff;">Votre paiement a échoué. Veuillez mettre à jour vos informations bancaires.</p><a href="#" style="background-color: #e50914; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px;">Mettre à jour</a></td></tr></table></body></html>`,
  },
  {
    id: 13,
    nom: "Apple - Achat suspect détecté",
    expediteur: "appleid@apple-security.com",
    objet: "Achat de 299€ sur l'App Store - Confirmez",
    contenuHtml: `<html><body style="font-family: -apple-system, BlinkMacSystemFont, sans-serif; background-color: #f5f5f7; padding: 20px;"><table style="max-width: 600px; margin: 0 auto; background-color: white; border-radius: 10px;"><tr><td style="padding: 20px;"><h3 style="margin-top: 0;">Achat détecté</h3><p>Un achat de 299€ a été enregistré sur votre compte.</p><a href="#" style="background-color: #0071e3; color: white; padding: 10px 20px; text-decoration: none; border-radius: 6px; display: inline-block;">Vérifier</a></td></tr></table></body></html>`,
  },
  {
    id: 14,
    nom: "Crédit Agricole - Sécurité renforcée",
    expediteur: "securite@ca-enligne.fr",
    objet: "Activation obligatoire de la double authentification",
    contenuHtml: `<html><body style="font-family: Arial, sans-serif; background-color: #f5f5f5; padding: 20px;"><table style="max-width: 600px; margin: 0 auto; background-color: white;"><tr style="background-color: #154873;"><td style="padding: 15px; color: white;"><h3 style="margin-top: 0;">Sécurité obligatoire</h3></td></tr><tr><td style="padding: 20px;"><p>Vous devez activer la double authentification sur votre compte.</p><a href="#" style="background-color: #154873; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px;">Activer maintenant</a></td></tr></table></body></html>`,
  },
  {
    id: 15,
    nom: "Société Générale - Opération bloquée",
    expediteur: "alerte@sg-banque.fr",
    objet: "Transaction de 1 250€ bloquée - Vérification nécessaire",
    contenuHtml: `<html><body style="font-family: Arial, sans-serif; background-color: #f5f5f5; padding: 20px;"><table style="max-width: 600px; margin: 0 auto; background-color: white;"><tr><td style="padding: 20px; border-left: 4px solid #d32f2f;"><h3 style="color: #d32f2f; margin-top: 0;">Transaction bloquée</h3><p>Une transaction de 1 250€ a été bloquée pour votre sécurité.</p><a href="#" style="background-color: #d32f2f; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px;">Débloquer</a></td></tr></table></body></html>`,
  },
];
